# Generated by Django 3.2.20 on 2023-07-26 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reservation',
            name='unique_booking',
        ),
        migrations.RenameField(
            model_name='picture',
            old_name='picrure',
            new_name='picture',
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.UniqueConstraint(fields=('user', 'date', 'time'), name='unique_reservation'),
        ),
    ]
